server:
  port: "8080"
  host: "localhost"
  timeout: 4s # seconds
  idle_timeout: 60s # seconds
db:
  DSN: "host=localhost port=5434 user=postgres password=postgres dbname=postgres sslmode=disable"

