server:
  port: 0
  host: ""
  timeout: 4s
  idle_timeout: 60s
  LOG_LEVEL: info # trace, debug, info, warning, error
  auth_service_url: "http://auth-service:8080"
db:
  DSN: "host= port= user= password= dbname= sslmode=disable"
  
# For production credentials use environment variables of secrets in Kubernetes/CI/CD. You can add env support via ${VAR}.
